spring.application.name=dailymotionminer
server.port = 8082
dailymotionminer.baseuri=https://api.dailymotion.com
dailymotionminer.maxVideos=10
dailymotionminer.maxPages=2
videominer.uri=http://localhost:8080/api