spring.application.name=dailymotionminer
server.port = ${PORT:8082}
dailymotionminer.baseuri=https://api.dailymotion.com
dailymotionminer.maxVideos=10
dailymotionminer.maxPages=2
videominer.uri=${VIDEOMINER_URL:http://localhost:8080}